### ISSUE TITLE
Schrijven over D3

### ISSUE THREAD

**Issue by kimgarrard** [kriskuiper/frontend-data#24]
Je kunt ook (dacht dat het verplicht was, maar weet dit niet zeker) in je wiki nog een aparte pagina maken over D3. Wat je ervan vind en hoe je ermee gewerkt hebt, inclusief stukjes code.

**Comment by kriskuiper** [comment]
Related to #30

**Comment by kriskuiper** [comment]
Not going to be that specific. Already explain how enter, update, exit works, only do something globally in the readme and refer to the code snippets further in the wiki
